spring: # default
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-admin-password: choshsh
logging:
  pattern:
    console: '%date%clr{faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
server:
  compression:
    enabled: true
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 14400
--- 
spring: # dev
  profiles: dev
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
  datasource:
    url: jdbc:h2:mem:itsmv
    driver-class-name: org.h2.Driver
    username: sa
    password: 
logging:
  level:
    com:
      itsmv: debug
    root: info
---
spring: # prod
  profiles:  prod
logging:
  level:
    com:
      itsmv: info
    root: info  
