spring: # default
  jpa:
    show-sql: false
    open-in-view: true
    hibernate:
      use-new-id-generator-mappings: true
logging:
  level:
    root: info
    com:
      itsmv: debug
    '[org.springframework.web]': debug
  pattern:
    console: '%date%clr{faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
server:
  compression:
    enabled: true
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 14400
    encoding:
      charset: UTF-8
      enabled: true
      force: true
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include:
          - metrics
          - health
---
spring: # dev
  profiles: dev
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    initialization-mode: always
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:itsmv
    username: sa
    password:
  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        web-admin-password: itsmv
---
spring: # prod
  profiles: prod
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    initialization-mode: always
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: jdbc:mysql://127.0.0.1:3306/itsmv?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: itsmv